Revert "add -Werror to CFLAGS"
This reverts commit a12e10b2595ae5e590ce3a4665cb8b5f1eee1338.

tcc will fail with -Werror due to a false positive:
> commands.c:66: error: function might return no value: 'cg_quit'