add github actions (#195)
* add github actions

this runs both default and minimal build with gcc and clang.
tcc seems to fail at link time for some reason.

* fix tcc build

* explicitly require xserver and libexif

* use 2 jobs instead of 6

* add -Werror to CFLAGS

* Revert "add -Werror to CFLAGS"

This reverts commit a12e10b2595ae5e590ce3a4665cb8b5f1eee1338.

tcc will fail with -Werror due to a false positive:
> commands.c:66: error: function might return no value: 'cg_quit'

* silence some non-useful output

* slience more non-useful info, add some useful ones

* use git clone --quiet

* remove newlines

* put core deps on single line

* cosmetic change

* prefer depth 1 clone